### ISSUE TITLE
can't add snippets and lack of understanding how this works

### ISSUE THREAD

**Issue by vesper8** [Reached/tweetsnippet#4]
Hi there! Just read about your story and this project as it was shared on Twitter today. Seems like a cool project and glad you open sourced it. I decided to check it out and ran into a few issues.

I installed it, ran composer install, created a database and ran the migrations. Then following your instructions.. well first of all you say to run 'php artisan user' but that returns an error saying there's no command 'user' and suggests make:user instead. I used make:user, did not even know this existed.. pretty useful and created a user.

I logged in by navigating to /login (there seems to be no login button in the navbar)

The login page seems to be missing some css and looks a bit odd. After logging in it sent me to a 404 page /home

I also noticed there is no /register page ?

Afterwards I tried to add a snippet. I wrote the twitter handle and added the twitter status url as seen in this screenshot. I then received an alert popup that wasn't helpful, it auto-populated the twitter ID field and then nothing.. the 'Store' button is still disabled and can't be clicked on

<img width="1438" alt="screenshot 2019-01-05 20 15 12" src="https://user-images.githubusercontent.com/816028/50728761-1b3ead80-1127-11e9-96ea-39869863e3b7.png">

So far that's as far as I've gotten. It's unclear how one can create snippet categories.

I also had the impression that this app pulls tweets from Twitter automatically but I guess that's not how it works and every snippet needs to be entered manually?

Would appreciate some feedback and looking forward to updates!

Thanks!!

**Comment by Reached** [comment]
Hi @vesper8,

Thanks for checking out Tweetsnippet :). 

> I installed it, ran composer install, created a database and ran the migrations. Then following your instructions.. well first of all you say to run 'php artisan user' but that returns an error saying there's no command 'user' and suggests make:user instead. I used make:user, did not even know this existed.. pretty useful and created a user.

I have fixed the issue of the missing make:user, thanks for reporting this!

So far that's as far as I've gotten. It's unclear how one can create snippet categories.

> So far that's as far as I've gotten. It's unclear how one can create snippet categories.

Currently you have to add Tags (there is a tags table) manually in the database, this is one of the shortcuts I took when I created the site. Feel free to open a pull request if you feel that you have the time to assist with this. Once you have added tags, they should show up when you go to the /create endpoint. 

> I logged in by navigating to /login (there seems to be no login button in the navbar)
> 
> The login page seems to be missing some css and looks a bit odd. After logging in it sent me to a 404 page /home
> 
> I also noticed there is no /register page ?

Intentionally there is no register page and no login link in the header (since this is an admin-only site for now).

> So far that's as far as I've gotten. It's unclear how one can create snippet categories.
> 
> I also had the impression that this app pulls tweets from Twitter automatically but I guess that's not how it works and every snippet needs to be entered manually?
> 
> Would appreciate some feedback and looking forward to updates!
> 
> Thanks!!

It will pull automatically from Twitter (that's the whole purpose), however I think Twitter changed something with their API, so I will have to look into this.

**Comment by Reached** [comment]
Also if you pull the project, you should now be able to run `php artisan db:seed`and two tags will be populated to the database.

**Comment by vesper8** [comment]
glad to see you are working on it and improving it :)

For the tags.. this might be overkill, however I have started using Laravel Backpack lately and it is so lovely and easy to use I'm now installing it to all my projects. Once you learn how it works you can add a full CRUD CMS for all your models in a matter of minutes! Definitely not at nice as having your own interface integrated into your web app however it's a lot nicer than having to connect to the tables and do manual inserts

Also.. the make:user command wasn't missing before.. now you've added dyrynda/laravel-make-user twice in the composer.json (duplicate key warning)

The issue is that in your instructions you said to call "php artisan user" and that just isn't the right command

As per the https://github.com/michaeldyrynda/laravel-make-user readme, it is indeed "php artisan make:user" which does work

**Comment by vesper8** [comment]
am happy to report that now that you've added the missing TwitterClient, I was able to add a snippet and the preview works fine through the API

I noticed if you visit a tag that doesn't have any snippets yet (https://tweetsnippet.dev/snippets/javascript for example) it throws this error
```
Route [contribute] not defined.
```

Also after logging in, it sends you to a /home 404 page, that should be changed to send you back to "/" instead

**Comment by Reached** [comment]
> For the tags.. this might be overkill, however I have started using Laravel Backpack lately and it is so lovely and easy to use I'm now installing it to all my projects. Once you learn how it works you can add a full CRUD CMS for all your models in a matter of minutes! Definitely not at nice as having your own interface integrated into your web app however it's a lot nicer than having to connect to the tables and do manual inserts

While I do agree that it would be nice to have a dedicated admin panel for Tweetsnippet, it's not something that I have needed, but feel free to make a pull request :)

>Also.. the make:user command wasn't missing before.. now you've added dyrynda/laravel-make-user 
twice in the composer.json (duplicate key warning)

Fixed.

> Also after logging in, it sends you to a /home 404 page, that should be changed to send you back to "/" instead

Actually, it should redirect to /create I think :) 

Also on a more general note I don't have much time to work on this project (code-wise), which is why I have open-sourced it if you feel like something is missing/wrong/buggy, you are more than welcome to submit pull requests :)
